pypro/aperitivos/urls.py
from django.urls import path

from pypro.aperitivos.views import video

app_name = 'aperitivos'
urlpatterns = [

    path('<slug:slug>', video, name='video'),

]

pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [

    path('', home, name='home'),

]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),


]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__', include(debug_toolbar.urls))

    )

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.
    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/aperitivos/views.py
from django.shortcuts import render


# Create your views here.
def video(request, slug):
    return render(request, 'aperitivos/video.html')

pypro/base/views.py
# Create your views here.
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

pypro/aperitivos/templates/aperitivos/video.html
{% load static %}
<!DOCTYPE html>
<!-- *home da pasta template .l.-->
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Python Pro</title>

    <meta name="description" content="Página do curso Python Pro">
    <meta name="author" content="Leandro Martins!">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
            integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
            integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
            crossorigin="anonymous"></script>


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            </ul>

        </div>
    </div>
</nav>


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3 "> Video Aperitivo: Motivação</h1>'
            <iframe class="border border-dark " src="https://player.vimeo.com/video/600226745?h=7bfc179ff6" width="640" height="360" frameborder="0"
                    allow="autoplay; fullscreen; picture-in-picture" allowfullscreen>

            </iframe>

        </div>
    </div>

</div>
<footer class="main-footer footer mt-5 pt-4 text-light " style="background-color:#9fd25f">
    <div class="container">
        <div class="row">
            <div class="col">

            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Entre em Contato</h3>
                <address>
                    +55 64 9 81073888
                    <br/>
                    <a href="mailto:lmsendmanil@gmail.com" class="text-primary">lmsendmanil@gmail.com</a>
                </address>

            </div>
        </div>
    </div>
    <div class="rights pb-4 " style="background-color:#82b641">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Python Pro. Todos direitos resevados!
                </div>
            </div>
        </div>
    </div>

</footer>

</body>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Entre em Contato</h3>
                <address>
                    +55 12 997-411-855
                    <br/>
                    <a href="mailto:{{contato_email}}" class="text-light">{{contato_email}}</a>
                </address>
            </div>
        </div>
    </div>
    <div class="rights pb-4">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Python Pro. Todos direitos reservados.
                </div>
            </div>
        </div>
    </div>
</footer>

pypro/base/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<!-- *home da pasta template .l.-->
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Python Pro</title>

    <meta name="description" content="Página do curso Python Pro">
    <meta name="author" content="Leandro Martins!">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
            integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
            integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
            crossorigin="anonymous"></script>


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            </ul>

        </div>
    </div>
</nav>


<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="jumbotron">
                <h2>
                    Curso de Python com Luciano Ramalho
                </h2>
                <p>
                    Mussum Ipsum, cacilds vidis litro abertis.
                <p> Praesent vel viverra nisi. Mauris aliquet nunc non turpis
                    scelerisque, eget. Detraxit consequat et quo num tendi nada.</p> Quem manda na minha terra sou
                euzis!
                Mais vale um bebadis conhecidiss, que um alcoolatra anonimis.
                <a href="https://tinyurl.com/livroPytho" target="_blank">Livro Python Fluente</a>
                </p>

            </div>
        </div>
    </div>


    <form class="form-inline float-lg-left">


        <div class="entrar_nome input-group mb-2 mr-sm-2 float-lg-left">

            <input type="text" class="form-control mb-2 mr-sm-2 " id="inlineFormInputName2"
                   placeholder=" Nome completo">

        </div>

        <div class="input-group mb-2 mr-sm-2 ">

            <input type="email" class="form-control" id="inlineFormInputGroupUsername2" placeholder="E-mail">

        </div>
        <small id="emailHelp" class="form-text text-muted">Nunca vamos compartilhar seu email, com ninguém.</small>

        <div class="form-check mb-2 mr-sm-2">
            <input class="form-check-input" type="checkbox" id="inlineFormCheck">
            <label class="form-check-label" for="inlineFormCheck">
                Lembrar me
            </label>
        </div>

        <button type="submit" class="btn btn-primary mb-2">Enviar</button>
    </form>

    <div class="button pagar mt-3 mb-3">
        <h4 class="mt-4">Matriculas Abertas! Custo R$1.000,00</h4>
        <div class="pagar"><label class=""> Garanta já sua Vaga pague em até 12 vezes com cartão</label></div>
        <script src="https://www.mercadopago.com.br/integrations/v1/web-payment-checkout.js"
                data-preference-id="79796750-5a535b03-fcd8-4071-949f-77cc75bebbfc" data-source="button">
        </script>

    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <h5 class="card-header">
                    Mais detalhe sobre o instrutor
                </h5>
                <div class="card-body">
                    <p class="card-text ">
                        <img src="{% static 'img/luciano-ramalho.png' %}" alt="Foto de Luciano Ramalho"
                             align="left" class="img-thumbnail float-left  margin-right:3px ">
                    <p class="float-left">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        A adipisci consectetur consequatur consequuntur dolorem enim magnam maiores non rem ut! Ad,
                        dicta ex fugit ipsam possimus suscipit temporibus tenetur.
                        Lorem ipsum dolore Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus
                        asperiores deleniti dicta dolor earum, incidunt laborum laudantium molestias perferendis porro
                        provident quibusdam, quos reiciendis saepe sed soluta tempora unde vitae?
                    </p>

                    </p>
                </div>

            </div>
        </div>
    </div>
</div>
<footer class="main-footer mt-5 pt-4 text-light " style="background-color:#9fd25f">
    <div class="container">
        <div class="row">
            <div class="col">

            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Entre em Contato</h3>
                <address>
                    +55 64 9 81073888
                    <br/>
                    <a href="mailto:lmsendmanil@gmail.com" class="text-primary">lmsendmanil@gmail.com</a>
                </address>

            </div>
        </div>
    </div>
    <div class="rights pb-4 " style="background-color:#82b641">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Python Pro. Todos direitos resevados
                </div>
            </div>
        </div>
    </div>

</footer>

</body>
</html>